#before nginx
version: "3"
services:
  nginx:
    image: nginx:stable-alpine
  node-app:
    build: .
    ports:
      - "4000:3000"
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - 6397

volumes:
  mongo-db:
