version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    environment:
      - PORT=5000
    depends_on:
      - mongo
    # not expose port in here because already has nginx 5000-80
  mongo:
    image: mongo
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis
    ports:
      - 6397

volumes:
  mongo-db:
